//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackatonGrupo02.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaDeAhorro
    {
        public int idCajaAhorro { get; set; }
        public string numero { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public decimal saldo { get; set; }
        public Nullable<int> idBanco { get; set; }
    
        public virtual Banco Banco { get; set; }
    }
}
