//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackatonGrupo02.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cupon
    {
        public int idCupon { get; set; }
        public Nullable<decimal> porcentajeDescuento { get; set; }
        public Nullable<int> idTarjeta { get; set; }
    
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
