//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackatonGrupo02.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorriente
    {
        public int idCuentaCorriente { get; set; }
        public string numero { get; set; }
        public decimal saldo { get; set; }
        public Nullable<int> idBanco { get; set; }
    
        public virtual Banco Banco { get; set; }

        public CuentaCorriente(string numero, decimal saldo, int? idBanco)
        {
            this.numero = numero;
            this.saldo = saldo;
            this.idBanco = idBanco;
        }
    }
}
