//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackatonGrupo02.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.Cupon = new HashSet<Cupon>();
        }
    
        public int idTarjeta { get; set; }
        public Nullable<int> idTipoTarjeta { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idBanco { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Banco Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cupon> Cupon { get; set; }
        public virtual TipoTarjeta TipoTarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
