//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackatonGrupo02.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
    

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dni { get; set; }
        public string usuario1 { get; set; }
        public string clave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarjeta> Tarjeta { get; set; }
        // constructor para alta
        public Usuario(string nombre, string apellido, string dni, string usuario1, string clave)
        {
            this.nombre = nombre;
            this.apellido = apellido;
            this.dni = dni;
            this.usuario1 = usuario1;
            this.clave = clave;
        }

        //constructor para ingreso
        public Usuario(string usuario1, string clave)
        {
            this.usuario1 = usuario1;
            this.clave = clave;
        }
        //usuario vacio
        public Usuario()
        {
            
        }


    }
}
